# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            HCI4
tagline:          Human-Computer Interaction
description:      Human-computer Interaction for Level 4 Glasgow University
url:              https://gu-cs-notes.github.io/HCI4
baseurl:          /HCI4				# Note! This should be the repo title preceded by a forward slash, but not followed by one! For example, the baseurl for AI4 is "/AI4"

author:
  name:           'Tom Wallis'

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/gu-cs-notes/blackdoc
